name: jku-ai-practical-project
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pytz
  - pip:
      - certifi
      - charset-normalizer
      - contourpy
      - cycler
      - einops
      - filelock
      - flash-linear-attention
      - fonttools
      - fsspec
      - hf-xet
      - huggingface-hub
      - hyper-connections
      - idna
      - jinja2
      - kiwisolver
      - local-attention
      - markupsafe
      - matplotlib
      - mpmath
      - networkx
      - pillow
      - pyparsing
      - python-dateutil
      - pyyaml
      - regex
      - requests
      - safetensors
      - six
      - sympy
      - tokenizers
      - tqdm
      - transformers
      - triton
      - triton-pascal
      - typing-extensions
      - tzdata
      - urllib3
      - jupyterlab
