#!/bin/bash

install_conda() {
    if command -v conda >/dev/null 2>&1; then
        echo "Conda already installed: $(command -v conda)"
        return 0
    fi

    echo "Conda not found. Installing Miniconda..."
    
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
    
    bash /tmp/miniconda.sh -b -p "$HOME/miniconda3"
    "$HOME/miniconda3/bin/conda" init bash
    
    source "$HOME/.bashrc"
    # Make conda available in current script
    source "$HOME/miniconda3/etc/profile.d/conda.sh"

    echo "Conda installed: $(command -v conda)"
}

git config core.hooksPath .githooks
git remote set-url origin https://mahdikhashan:$(cat TOKEN)@github.com/mahdikhashan/jku-ai-practical-project.git

git config --global user.email "mahdikhashan1@gmail.com"
git config --global user.name "Mahdi Khashan"

install_conda

conda env create -f environment.yaml
